name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Set up Xvfb
      run: |
        choco install xvfb
        Xvfb :0 -ac -screen 0 1024x768x24 &
        
    - name: Test
      run: |
        dotnet test SpecFlowProject1
